# Generated by Django 5.0.1 on 2024-02-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_portfolio_users_portfolio_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
