# Generated by Django 5.0.1 on 2024-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_portfolio_users_portfolio_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Metadata',
            fields=[
                ('ticker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
