# Generated by Django 5.0.1 on 2024-02-08 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_actor_profit_evolution_actors_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_transactions',
            fields=[
                ('id_transaction', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('transaction_date', models.DateField()),
                ('conversion_rate', models.FloatField()),
                ('transaction_price', models.CharField(max_length=100)),
                ('charges', models.FloatField()),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.portfolio')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stock_metadata')),
            ],
        ),
    ]
