# Generated by Django 5.0.1 on 2024-02-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_stock_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_portfolio',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
