# Generated by Django 5.0.1 on 2024-02-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_stock_portfolio_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_portfolio',
            name='name_stock',
        ),
    ]
