# Generated by Django 5.0.1 on 2024-02-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_portfolio_id_actors_cashflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors_cashflow',
            name='portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.actors_portfolio'),
        ),
    ]
