# Generated by Django 5.0.1 on 2024-02-10 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_actors_cashflow_portfolio_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors_cashflow',
            new_name='Actors_transaction',
        ),
    ]
