# Generated by Django 5.0.1 on 2024-02-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_actors_portfolio_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor_profit_evolution',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.holder'),
        ),
        migrations.AlterField(
            model_name='actors_portfolio',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.holder'),
        ),
        migrations.AlterField(
            model_name='actors_transaction',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.holder'),
        ),
    ]
