# Generated by Django 4.2.11 on 2024-03-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_actor_profit_evolution_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.portfolio'),
        ),
    ]
